### PR TITLE
Adds `assertEquals()` and `guard()` functions

### PR DESCRIPTION
**Pull request by twof**
Let me know if you want them moved into their own extension files. Example usage:

```swift
User.query(on: req)
    .filter(\.email == registerRequest.email)
    .count()
    .assertEquals(0)
    .guard(elseThrow: userExistsError)
    .saveUserWith(
        name: registerRequest.name,
        email: registerRequest.email,
        password: registerRequest.password,
        on: req
    )
```

### CODE REVIEW

**Comment by bensyverson** [comment]
I'm still seeing weird behavior where an exception within `guard` is not bubbling up. Check out this [example project](https://gitlab.com/bensyverson/miiine/tree/c284433d8d4af6803bd7074c0f5e5b7f41db54f4) which uses the proposed change. You'll need to reconfigure psql, then register a new User (call `/api/v1/register` or use the included Paw file).

Registering multiple users with the same email address should be prevented by `guard`, but it passes through. The console will read `I should throw!`—which is printed from the same block that throws the Error—but the Error (an Abort) is silently caught somewhere, allowing the chain to continue with a successful `200`

**Comment by twof** [comment]
In reference to @bensyverson's issue, there seems to be a problem where `Abort`s thrown earlier in the chain will be overridden buy errors thrown later in the chain.

**Comment by twof** [comment]
Added a variadic version of `assertEquals` and made `guard`'s result discardable so you can now do things like validate query results. Example:

```
extension QueryBuilder where Model == Reservation {
    func validNumberOfReservationsInDatabase() -> Self {
        let invalidNumberOfReservationsError = Abort(.badRequest, reason: "There are an unusual number of reservations matching that query in your DB", identifier: "Whoops")
        
        self
            .count()
            .assertEquals(0, 1)
            .guard(elseThrow: invalidNumberOfReservationsError)
        
        return self
    }
}
```

In this example I'm checking to see if the number of `Reservation`s returned is either 0 or 1 and `Abort`ing if that's not the case.

**Comment by tanner0101** [comment]
I like these methods, but not convinced (yet) they are critical enough to require in the core. These strike me as suitable for addition in a third party "helpers" package.

**Comment by Joannis** [comment]
I concur with @tanner0101

**Comment by jdmcd** [comment]
@twof Maybe you can start a helpers package in `vapor-community`?

**Comment by twof** [comment]
@mcdappdev I'm down. Do I need to be added to the organization or how does that work?

**Comment by jdmcd** [comment]
I believe so but I'm not positive

**Comment by twof** [comment]
Hey I'm still down to maintain (or comaintain) a repo in vapor-community if someone wants to open an `AsyncHelpers` repo for me

@tanner0101 @Joannis 

CC @MaximBazarov

**Comment by gperdomor** [comment]
@twof @tanner0101 @Joannis @mcdappdev @bensyverson I made a repo with some extensions, please make PR for new extensions here --> https://github.com/vapor-community/vapor-extensions

**Comment by twof** [comment]
CC @MaximBazarov

**Comment by gperdomor** [comment]
I think we can close this in favor of https://github.com/vapor-community/async-extensions

**Comment by twof** [comment]
Closing this PR now that there's a community extensions package

**Pull request closed without merging**
